version: '3.8'
services:
  api:
    build: ./api
    container_name: api_backend
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app
  front-end:
    build: ./front-end
    container_name: client_frontend
    ports:
      - '3000:3000'
    volumes:
      - ./front-end:/app
    stdin_open: true
    tty: true